#+TITLE: Strutture di Yoneda e accessibilità
#+AUTHOR: Fosco Loregian

#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{eucal}
#+LATEX_HEADER: \usepackage{tikz-cd}
#+LATEX_HEADER: \hyphenation{mo-no-i-da-le}
#+LATEX_HEADER: \def\C{\mathcal{C}}
#+LATEX_HEADER: \usepackage[all,2cell]{xy}\UseAllTwocells
#+LATEX_HEADER: \def\Cat{\mathsf{Cat}}
#+LATEX_HEADER: \def\Set{\mathsf{Set}}
#+LATEX_HEADER: \def\xto#1{\xrightarrow{#1}}
#+LATEX_HEADER: \def\xot#1{\xleftarrow{#1}}
#+LATEX_HEADER: \def\To{\Rightarrow}
#+LATEX_HEADER: \usepackage[all,2cell]{xy}
#+LATEX_HEADER: \newcommand{\deduction}[4]{\begin{array}{c} #1 \to #2 \\ \hline #3 \to #4 \end{array}}
#+LATEX_HEADER: \newcommand{\Nearrow}{\rotatebox[origin=c]{45}{$\Rightarrow$}}  % ↗
#+LATEX_HEADER: \newcommand{\Nwarrow}{\rotatebox[origin=c]{135}{$\Rightarrow$}} % ↖ 
#+LATEX_HEADER: \newcommand{\Searrow}{\rotatebox[origin=c]{-45}{$\Rightarrow$}} % ↘
#+LATEX_HEADER: \newcommand{\Swarrow}{\rotatebox[origin=c]{225}{$\Rightarrow$}} % ↙
#+LATEX_HEADER: \newcommand{\Sarrow}{\rotatebox[origin=c] {-90}{$\Rightarrow$}}
#+LATEX_HEADER: \newcommand{\Narrow}{\rotatebox[origin=c] {90}{$\Rightarrow$}}
#+LATEX_HEADER: \usepackage{turnstile}
#+LATEX_HEADER: \newcommand{\adjunct}[2]{\nsststile{#2}{#1}}
#+LATEX_HEADER: \def\opp{\mathrm{op}}
#+LATEX_HEADER: \def\co{\mathrm{co}}
#+LATEX_HEADER: \def\coop{\mathrm{coop}}
#+LATEX_HEADER: \def\rift{\mathrm{rift}}
#+LATEX_HEADER: \def\leeft{\mathrm{lift}} % `lift is already something!
#+LATEX_HEADER: \def\lan{\mathrm{lan}}
#+LATEX_HEADER: \def\ran{\mathrm{ran}}
#+LATEX_HEADER: \def\Rift{\mathrm{Rift}}
#+LATEX_HEADER: \def\Lift{\mathrm{Lift}}
#+LATEX_HEADER: \def\Ran{\mathrm{Ran}} 
#+LATEX_HEADER: \def\Lan{\mathrm{Lan}}
#+LATEX_HEADER: \def\RIFT{\textsc{rift}}
#+LATEX_HEADER: \def\LIFT{\textsc{lift}}
#+LATEX_HEADER: \def\RAN{\textsc{ran}}
#+LATEX_HEADER: \def\LAN{\textsc{lan}}
#+LATEX_HEADER: \usepackage{amsthm}
#+LATEX_HEADER: \theoremstyle{reference}
#+LATEX_HEADER:   \newtheorem{theorem}{Theorem}[section]
#+LATEX_HEADER:   \newtheorem{definition}[theorem]{Definizione}
#+LATEX_HEADER:   \newtheorem{axiom}[theorem]{Assioma}
#+LATEX_HEADER:   \newtheorem{lemma}[theorem]{Lemma}
#+LATEX_HEADER:   \newtheorem{proposition}[theorem]{Proposizione}
#+LATEX_HEADER:   \newtheorem{remark}[theorem]{Osservazione}
#+LATEX_HEADER: \hypersetup{colorlinks=true, linkcolor=black}



* Lecture I: Introduzione
** 2-categorie: def di partenza
Una /2-categoria/ è ``come una categoria, ma gli hom-set
sono categorie'': si tratta di un certo tipo di struttura
2-dimensionale che soddisfa le seguenti ipotesi

1. E' data una classe di oggetti $\mathcal K_0$,
2. E' dato per ogni coppia di oggetti $X,Y\in \cal K_0$ un
   insieme di morfismi (o /1-celle/) ${\cal K}(X,Y)$
3. E' data una regola di composizione
$$ c_{XYZ} : {\cal K}(X,Y)\times {\cal K}(Y,Z) \to {\cal K}(X,Z) $$ che sia
/bifuntoriale/, ossia tale esista una regola di composizione orizzontale, una
verticale, e tali che per esse valga la ``regola di interscambio di Godement'':
$$ \xymatrix{A \ruppertwocell{\beta} \ar[r]\rlowertwocell{\delta}& B
\ruppertwocell{\alpha} \ar[r]\rlowertwocell{\gamma}& C} $$
$$ (\alpha *\beta)\circ (\gamma * \delta) = (\gamma \circ\alpha) * (\delta \circ
\beta)$$
Una 2-categoria è una categoria arricchita su $\Cat$, guardata come base
monoidale (chiusa): ogni $\Cat({\cal C},{\cal D})$ è a sua volta una categoria,
i cui oggetti sono i funtori $F,G : \C\to {\cal D}$ e i cui morfismi sono le
trasformazioni naturali. Ciascuna composizione è ``bilineare'', ed esiste una
nozione di funtore arricchito (/2-funtore stretto/) e di trasformazione naturale
arricchita (/trasf. naturale stretta/).

La teoria delle 2-categorie coincide allora con la teoria
delle $\Cat$ -categorie? In parte sì: un gran numero di
risultati è conseguenza della teoria generale sviluppata nel
primo capitolo. Del resto, una parte ancora maggiore di
risultati non si può ingabbiare nel linguaggio delle
categorie arricchite: e questo perché segretamente la
collezione delle 2-categorie (di cui, fatti salvi alcuni
problemi di teoria degli insiemi, $\Cat$ è un oggetto) è una
*3-categoria*; le sue proprietà sono quindi più naturalmente
descritte da strutture e leggi di coerenza più blande di
quelle che sostengono la teoria delle $\Cat$ -categorie.

Un esempio su tutti: nei termini di una $\Cat$ -categoria è
complicato (o impossibile?) descrivere come faccia un
diagramma a commutare /a meno di una trasformazione
naturale/ -invertibile o meno.

Alcune osservazioni:

+ Ogni 2-categoria dà luogo ad altre 2-categorie $\mathcal K^\co, \mathcal
  K^\opp$ dove rispettivamente sono state invertite le frecce in dimensione 2
  ed 1. Più formalmente, $\mathcal K^\co$ è una 2-categoria ottenuta da
  $\mathcal K$ che ha gli stessi oggetti e dove $\mathcal K^\co(X,Y) = \mathcal
  K(X,Y)^\opp$, e $\mathcal K^\opp$ è una 2-categoria con gli stessi oggetti di
  $\mathcal K$, dove $\mathcal K^\opp(X,Y) = \mathcal K(Y,X)$. Chiaramente,
  $(\mathcal K^\opp)^\co = (\mathcal K^\co)^\opp = \mathcal K^\text{coop}$.
+ Gli oggetti di $\mathcal K$ si dicono \emph{0-celle}; gli oggetti delle categorie ${\mathcal K}(X,Y)$ si dicono 1-celle (di dominio $X$ e codominio $Y$); i morfismi delle categorie ${\mathcal K}(X,Y)$ si dicono 2-celle di $\mathcal K$.

** Estensioni e lift di Kan

\begin{definition}
Let $B \xto{f} A \xot{g}C$ a cospan of
1-cells in ${\mathcal K}$. A /left lifting/ of $f$ along $g$
consists of a pair $\langle\leeft_gf,\eta\rangle$ (often
denoted simply as $\leeft_gf$) initial among the commutative
triangles like the one below: 
\[
\vcenter{\xymatrix@C=1.4cm{& C\ar[d]^g \\ B\ar[r]_f
\ar@{.>}[ur]^{\leeft_gf} & \ar@{}[ul]|(.3){\Nearrow\eta} A}}
\qquad \deduction{\leeft_gf}{h}{f}{gh} 
\] In other words,
composition with $\eta \colon f \To g \circ \leeft_gf$
determines a bijection $\bar\gamma \mapsto (g *
\bar\gamma)\circ \eta$ between 2-cells $\leeft_gf
\xto{\bar\gamma} h$ and 2-cells $f \to gh$.
\end{definition}

Si può anche definire un \emph{lifting destro} in maniera simile, rovesciando la direzione delle sole 2-celle nel diagramma precedente, e le \emph{estensioni sinistre} e \emph{destre} rispettivamente rovesciando solo la direzione delle 1-celle, o la direzione di entrambe nel diagramma precedente. E' quindi chiaro che le estensioni sinistre sono lifting sinistri in ${\mathcal K}^\opp$, i lifting destri in ${\mathcal K}$ sono lifting sinistri in ${\mathcal K}^\co$, e le estensioni destre sono lifting sinistri in ${\mathcal K}^\coop$.

\begin{center}
\begin{array}{|c|c|}\hline \xymatrix{A \ar@{}[dr]|(.3){\Swarrow\eta}\ar[d]_g
\ar[r]^f& B \\ C \ar@{.>}[ur]_{\Lan_gf} & {\tiny \deduction{\Lan_gf}{h}{f}{hg}}}
& \xymatrix{{\tiny \deduction{\Lift_gf}{h}{f}{gh}} & C\ar[d]^g \\ B\ar[r]_f
\ar@{.>}[ur]^{\Lift_gf} & \ar@{}[ul]|(.3){\Nearrow\eta} A} \\ \hline
%%%
\xymatrix{A \ar@{}[dr]|(.3){\Nearrow\varepsilon}\ar[d]_g \ar[r]^f& B \\ C
\ar@{.>}[ur]_{\Ran_gf} & {\tiny \deduction{hg}{f}{h}{\Ran_gf}}} &
\xymatrix{{\tiny \deduction{h}{\Rift_gf}{gH}{f}} & C\ar[d]^g \\ B\ar[r]_f
\ar@{.>}[ur]^{\Rift_gf} & \ar@{}[ul]|(.3){\Swarrow\varepsilon} A} \\ \hline
\end{array}
\end{center}

\begin{definition}[Estensione/lift preservato/assoluto]

\end{definition}

** Caratterizzazione degli aggiunti mediante estensioni e lift

Qui ci proponiamo di dimostrare una caratterizzazione degli
aggiunti in termini di lift ed estensioni. Si tratta di un
esercizio elementare nelle proprietà universali in una
2-categoria, che svolgiamo nei dettagli per fare entrare il
lettore nella semantica delle 2-categorie.

\begin{proposition}
Le seguenti condizioni sono equivalenti per una coppia di 1-celle $f : A \leftrightarrows B : g$
\begin{itemize}
\item $f \dashv g$ con unità $\eta$ e counità $\epsilon$;
\item La coppia $\langle g,\eta\rangle$ esibisce la Lan assoluta di $1$ lungo $f$
\item La coppia $\langle g,\eta\rangle$ esibisce la Lan di $1$ lungo $f$, ed $f$ la preserva.
\end{itemize}
\end{proposition}
\begin{proof}
E' evidente che 2 implica 3; mostriamo che 1 implica 2. Dato il diagramma
$$
\xymatrix{
A \ar@{=}[r]\ar@{}[dr]|(.3){\Swarrow\eta}\ar[d]_f & A  \\
B \ar[ur]_g & 
}
$$
dobbiamo mostrare che è una Lan assoluta. Del resto,  se $f \dashv g$, dato $h : B\to A$ con una trasformazione $\alpha : 1\To hf$, le identità triangolari implicano che la composizione $\bar\alpha : g \overset{\alpha * g} \To hfg \overset{h * \epsilon}\To h$ sia tale che $(\bar \alpha * f)\circ \eta = \alpha$. Tale scelta è unica, perché se $\bar\alpha$ e $\hat\alpha$ hanno la stessa proprietà, basta incollare la counità per vedere che $\bar \alpha * g = \hat\alpha * g$:
$$
\vcenter{\xymatrix{
& A \rrlowertwocell<\omit>{<3>\eta} \ar[dr]_f\ar@{=}[rr] & & A \\
B \rruppertwocell<\omit>{<-3>\epsilon} \ar[ur]^g\ar@{=}[rr] && B \ar[ur]^g\urlowertwocell{\bar\alpha} & 
}}
\quad = \quad
\vcenter{\xymatrix{
& A \rrlowertwocell<\omit>{<3>\eta} \ar[dr]_f\ar@{=}[rr] & & A \\
B \rruppertwocell<\omit>{<-3>\epsilon} \ar[ur]^g\ar@{=}[rr] && B \ar[ur]^g\urlowertwocell{\hat\alpha} & 
}}
$$
Un argomento simile mostra che l'estensione è assoluta: dato un diagramma come
\[
\xymatrix{
A \ar@{=}[r]\ar[d]_f & A \ar[r]^u  & X \\
B  \ar@/_1pc/[urr]_h \ar[ur]_g& &
}
\]
riempito da una 2-cella $\alpha : u \To hf$, va mostrato che esiste un'unica $\bar\alpha : ug\To h$ tale che $\alpha = (\bar\alpha * f)\circ(u * \eta)$. Tale freccia è presto vista essere $(h * \epsilon)\circ(\alpha *g)$.

Ora mostriamo che 3 implica 1. Se $\langle fg, f *\eta\rangle$ esibisce $\lan_ff$, allora è automatico che esista un'unica $\epsilon : fg\To 1$ tale che $(\epsilon * f)\circ (f * \eta) = 1_f$; per quanto riguarda l'altra identità triangolare\dots
\end{proof}
Valgono condizioni duali che si possono riassumere nel seguente specchietto:
\begin{center}
\includegraphics{adjs}
\end{center}
** Il sacro pasting lemma

Uno dei trucchi tecnici più utili è il seguente: si chiama /pasting lemma/. La dimostrazione si fa verificando la proprietà universale giusta.
\begin{proposition}
Dato un diagramma come
$$
\begin{tikzcd}
|[alias=a]|A \ar[r,"h"]\ar[d,"f"']&|[alias=d]| D &|[alias=a']| A \ar[d]\ar[r,"h"]&|[alias=d']| D \\
B \ar[d,"g"']\ar[ur]&&|[alias=b']| B \ar[d]\ar[ur]\\
|[alias=c]|C \ar[bend right,uur] && C\ar[bend right,uur] 
\end{tikzcd}
$$
se il triangolo esterno e quello superiore sono estensioni di Kan, tale è anche il rimanente triangolo.
\end{proposition}

** Strutture di Yoneda e FCT: il lemma di Yoneda come pilastro del pensiero occidentale

*** Yoneda nel senso classico; Yoneda "per i baby geometri"
Il lemma di Yoneda come viene insegnato nelle scuole inferiori, asserisce che
dato un prefascio $F : \C^\opp \to \Set$ e un oggetto $c\in\ C$ esiste un isomorfismo naturale
in $c$
$$
Nat(y(c), F)\cong Fc
$$
dove $y : \C \to [\C^\opp,\Set]$ è l'embedding di Yoneda che manda $c$ nel prefascio $\C(-,c)$.

Ora, lungi dall’essere un mero teorema di matemaitca, questo asserto costituisce
uno dei punti più elevati raggiunti dal pensiero occidentale nella sua
totalità. Diverse generazioni di studio sono state completamente insufficienti
a disvelarne le incredibili conseguenze.

Quello che facciamo noi ora è

+ Scrivere il lemma di Yoneda in forma fibrazionale;
+ Capire in che cosa consiste quando i prefasci vengono interpretati come fibrazioni

Per farlo ci avvaliamo di questo risultato:

\begin{proposition}
Esiste un’equcat tra $[\C^\opp,\Set]$ (la categoria dei prefasci
su $\C$) e la categoria delle /fibrazioni discrete/ su $\C$ (una fibrazione discreta
è un funtore $p : \mathcal E \to \C$ tale che ogni fibra $p^\leftarrow(c)$ sia una categoria discreta).
\end{proposition}
\begin{proof}
E' sufficiente dimostrare che esiste una coppia di funtori in direzioni opposte 
$$
[\C^\opp,\Set] \leftrightarrows \text{DFib}(\C)
$$
le cui composizioni nei due sensi siano isomorfe alle rispettive identità (perché?). Per farlo, definiamo ${\mathfrak E} : [\C^\opp,\Set] \to \text{DFib}(\C)$ mandando $P$ nella sua categoria degli elementi; in direzione opposta, definiamo ${\mathfrak F} : \text{DFib}(\C) \to [\C^\opp,\Set]$ mandando $p : \mathcal E\to \C$ nel prefascio determinato da $\lambda c.p^\leftarrow(c)$ (dal momento che $p$ è una fibrazione discreta, questa corrispondenza è davvero un funtore). E' evidente che $\mathfrak{EF}\cong 1$, così come $\mathfrak{FE}\cong 1$.
\end{proof}
In tale contesto il lemma di Yoneda diventa il seguente enunciato:
\begin{lemma}[Yoneda fibrazionale]
C'è una biiezione
$$\left\{
{\small 
\vcenter{
  \xymatrix@!=3mm{
  \C/c \ar@{.>}[rr]\ar[dr]_U && \mathfrak E(P)\ar[dl]^\pi \\
  & \C & 
  }
}}
\right\} \cong Pc$$
tra le frecce tratteggiate e gli elementi di $Pc$.
\end{lemma}
\begin{proof}
Esercizio.
\end{proof}
*** Di cosa parliamo quando parliamo di teoria delle categorie?
Che cos’è la teoria delle categorie? Nelle parole di John Gray,
\begin{quote}
The purpose of category theory is to try to describe certain general
aspects of the structure of mathematics. Since category theory
is also part of mathematics, this categorical type of description
should apply to it as well as to other parts of mathematics.

[O]ne should attempt to identify those properties that enable one
to do the "structural parts of category theory".
\end{quote}
Che cosa significa questo? Sostanzialmente che la teoria delle categorie
"astratta" è quell’insieme di asserti che riguardano il comportamento di
strutture che si comportano come la 2-categoria paradigmatica $\Cat$ (allo
stesso modo, la teoria delle categorie "concreta" consta di quegli asserti che
riguardano categorie che si comportano come quelle di oggetti matematici
quotidiani: la categoria degli insiemi, quella dei gruppi abeliani, dei monoidi,
degli insiemi o spazi vettoriali con una azione di gruppo. . . ).
Analogamente a quel che succede quando si usa la teoria delle categorie
per chiarificare la matematica classica (in modo che le proprietà degli oggetti
matematici diventino proprietà universali, e che queste proprietà universali
siano godute dagli oggetti di una categoria, definendo, ad esempio, la semantica
funtoriale delle teorie algebriche), la teoria delle 2-categorie fa lo
stesso lavoro con la teoria delle categorie. Alle entità fondamentali della teoria
delle categorie (gli aggiunti e il loro calcolo, le monadi, le estensioni di Kan, il calcolo dei co/limiti\dots) viene data licenza di esistere non più nella
2-categoria $\Cat$, ma in una generica 2-categoria $\mathcal K$.
La nozione di struttura di Yoneda nasce per dare conto di queste affermazioni
e concretizzarle in una teoria esplicita e computabile: prendiamo
come assiomi fondamentali di questa religione il fatto che

+ la teoria delle categorie coincide con l’insieme dei corollari del lemma
di Yoneda;
+ E’ possibile enunciare un insieme finito di assiomi capaci di catturare
le varie facce del lemma di Yoneda;
+ L’intero comparto di tecniche della CT formale nasce per rispondere a
questa domanda: qual è il minimo amount di struttura addizionale da
mettere su una 2-categoria $\mathcal K$ per fare in modo che esistano, in $\mathcal K$, delle
1-celle che giocano lo stesso ruolo delle fibrazioni discrete, dando a $\mathcal K$
una versione fibrazionale del lemma di Yoneda?

** Assiomi di struttura di Yoneda

Gli assiomi sono 4. Seguiamo questo pattern:

+ Come zeresimo passo, listiamo i dati che K deve possedere; questi dati formano un telaio di Yoneda.
+ Prima enunciamo l’assioma;
+ Poi mostriamo perché è vero in $\Cat$ (la risposta sarà che l’assioma è una conseguenza del lemma di Yoneda, in un modo o nell’altro);
+ Poi enucleiamo alcuni corollari di quell’assioma.

\begin{definition}
Affinché K abbia un telaio di Yoneda essa deve essere equipaggiata di questi dati:
\begin{itemize}
\item Un ideale di morfismi "ammissibili"; le frecce identiche nell’ideale specificano
gli /oggetti/ ammissibili.
\item Per ogni oggetto ammissibile $A$ una "freccia di Yoneda" $y_A : A \to P A$ verso un oggetto che chiamiamo "oggetto dei prefasci" di $A$;
\item per ogni morfismo ammissibile $f : A\to B$ con dominio ammissibile un triangolo
$$
\xymatrix{
  &A \ar[dr]^f\ar[dl]_{y_A}&\\
PA \urlowertwocell<\omit>{<3>\quad\chi^f}&&\ar[ll]^{B(f,1)} B
}
$$
\end{itemize}
\end{definition}
\begin{axiom}
La coppia $\langle B(f,1), \chi^f\rangle$ esibisce $\lan_fy_A$.
\end{axiom}
Perché è vero in $\Cat$? E' il lemma di Yoneda, nella forma che asserisce l'esistenza di un funtore $N_f = B(f,1) : \lambda b.(\lambda a. B(fa,b))$, detto \emph{$f$-nervo}. Ad esempio, quando $f : \Delta \to \Cat$ è il funtore che realizza ogni ordinale finito come una categoria, $\Cat(f,A)$ è il \emph{nervo} della categoria $A\in\Cat$, che manda $n$ in $\Cat([n],A)$.
\begin{proof}
Bisogna mostrare l'isomorfismo $$[B,PA](N_f,G) \cong [A,PA](y_A,G\circ f).$$
Per farlo, è sufficiente considerare l'isomorfismo integrale
\begin{align*}
[B,PA](N_f,G) &\cong \int_b PA(B(f,b),Gb)\\
&\cong \int_{ab} \Set(B(fa,b), G(b)(a))\\
&\cong G(fa)(a)\\
[A,PA](y_A,G\circ f) & \cong \int_a PA(y_A(a), G(fa))\\
&\cong G(fa)(a).
\end{align*}
E' ovviamente possibile una dimostrazione diretta, con la proprietà universale: la lasciamo come esercizio.
\end{proof}
\begin{axiom}
La coppia $\langle f, \chi^f\rangle$ esibisce $\leeft_{B(f,1)}y_A$.
\end{axiom}
Perché è vero in $\Cat$? E' il lemma di Yoneda, nella forma che asserisce che vale l'isomorfismo
\begin{align*} 
[A,PA]\big( y_A, N_f\circ g \big) &\cong \int_{a'}[A^\opp,\Set]\big(y_A{a'}, N_f\circ g(a')\big)\\ 
& \cong \int_{a'}[A^\opp,\Set]\big( y_A{a'}, B(f\firstblank,ga')\big)\\ 
&\cong \int_{a'}B(fa',ga')\\ &\cong [A,B](f,g)
\end{align*}
E' ovviamente possibile una dimostrazione diretta, con la proprietà universale: la lasciamo come esercizio.
\begin{axiom}
Given a pair of composable 1-cells $A \xto{f} B\xto{g} C$, the
pasting of 2-cells
$$ \begin{tikzcd}[column sep=large, row sep=large] A\ar[d, "f"']\ar[rr, "y_A"{name=yonA}] && P A\\ B \ar[r, "y_B"{name=yonB}]\ar[d, "g"'] & P B\ar[ur, "P f"']\\ C\ar[ur, "{C(g,1)}"'] \ar[from=yonA, to=yonB, shorten >=2mm, shorten <=4mm, Rightarrow, "\chi^{y_B f}"] \ar[from=yonB, shorten >=4mm, shorten <=4mm, Rightarrow, "\chi^g"] \end{tikzcd} $$
exhibits $\lan_{gf}y_A = C(gf,1)$.
\end{axiom}
Perché è vero in $\Cat$? Pasting lemma delle estensioni.
\begin{axiom}
La coppia $\langle 1_{PA}, 1_{y_A} \rangle$ esibisce $\lan_{y_A}y_A$.
\end{axiom}
Perché è vero in $\Cat$? E' il lemma di Yoneda, nella forma che asserisce che l'embedding di Yoneda è un funtore \emph{denso}.
\begin{proof}
Si potrebbe fare con gli integrali usando ancora la formula puntuale per le Lan, ma una dimostrazione diretta è illuminante. Srotolando la proprietà universale, va dimostrato che una trasformazione naturale $\alpha : 1_{PA} \To H$ è univocamente determinata dalla sua restrizione alle componenti rappresentabili (nell'immagine essenziale di $y_A$, che sappiamo già essere pienamente fedele). Ora, data una $\beta : y_A\To Hy_A$ dobbiamo dimostrare che essa è $\alpha *y_A$ per un'unica $\alpha : 1\To H$; per farlo possiamo ricordare che ogni $P : A^\opp\to \Set$ è colimite di rappresentabili, e precisamente $P \cong \varinjlim\!{}^Py_A$; sicché la componente di $\beta$ si può estendere a
$$
P \cong \varinjlim\!{}^P y_A \xto{\varinjlim{}^P\beta} \varinjlim\!{}^P H y_A \to H(\varinjlim\!{}^P  y_A ) \cong HP
$$
Che queste siano le componenti di una trasformazione naturale $1 \To H$ è presto verificato.
\end{proof}
** Alcuni teoremi veri in una YS

Ora possiamo definire diverse nozioni che non avevano un analogo controllabile prima di scoprire che $\mathcal K$ supportava una teoria delle categorie.

\begin{definition}[Estensioni puntuali e assolute]
Blah 
\end{definition}
\begin{definition}[Caratterizzazione puntuale degli aggiunti]
Blah 
\end{definition}

** La nozione di P-cocompletezza

Negli assiomi di YS è nascosto il fatto che $PA$ ha la proprietà universale del cocompletamento libero di $A$: dove? E' magari possibile dimostrare che un oggetto $X$ è cocompleto se e solo se tutte le 1-celle $A\to X$ si estendono a una aggiunzione $PA \leftrightarrows X$? La risposta è sì, ma affinché sia vero $PA$ deve essere "cocompleto rispetto a sé stesso".

\begin{definition}[Oggetto co/completo]
Un oggetto $X\in \mathcal K$ si dice \emph{cocompleto} quando 
\end{definition}
** Categorie accessibili e presentabili, classicamente?
\begin{definition}[Categoria accessibile]

\end{definition}
\begin{definition}[Categoria presentabile]

\end{definition}
\begin{definition}[Teorema di rappresentazione, I]

\end{definition}
\begin{definition}[Teorema di rappresentazione, II]

\end{definition}
\begin{definition}[Dualità di Gabriel-Ulmer]

\end{definition}
* Lecture II: Accessibility and Presentability in 2-categories
** Cosa vogliamo fare
Le categorie accessibili e presentabili sono particolari
oggetti della 2-categoria $\Cat$; fino a che punto è possibile
sketchare una definizione per un oggetto
accessibile/presentabile di una 2-categoria $\mathcal K$? E' ancora
possibile recuperare i teoremi classici di rappresentazione,
che dicono come gli oggetti accessibili nascano da
riflessioni di oggetti dei prefasci?

E' ancora possibile enunciare e dimostrare la dualità di
Gabriel-Ulmer, ossia la biequivalenza tra la sub-2-categoria
degli oggetti presentabili di K e la 2-categoria degli
"oggetti con limiti finiti"?

** L'idea per farlo

Utilizzare il linguaggio delle strutture di Yoneda; il teorema classico di "rappresentazione" che dice che una categoria è presentabile se e solo se 

** Definizione: Yoneda context
** Definizione: oggetto accessibile wrt un contesto
** Definizione: oggetto presentabile wrt un contesto
** Faint presentability: non più equivalente alla presentabilità forte
** ...Ma sono equivalenti in un GU-envelope!...
** ...che è esattamente il setting dove vale GU
** Esempi, tantissimi esempi
** Long term goal: derivatori e infty-categorie
